version: '3'

# networks:
#   app-tier:
#     driver: bridge

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    # networks:
    #   - app-tier
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    links:
      - "postgres:db"

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # networks:
    #   - app-tier

  # websockets:
  #   build: ./backend
  #   command: >
  #     sh -c "python3 echo_server.py"
  #   volumes:
  #     - ./backend:/code
  #   ports:
  #     - "7000:7000"
  #   depends_on:
  #     - db
  #     - backend

# cool stuff here:
# https://github.com/Telling/docker-django/blob/master/entrypoint
# python3 manage.py wait_for_db &&