version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: ./back-end
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  node:
    build: 
      context: ./front-end
    command: "npm start"
    volumes:
      - ./front-end:/usr/app
      - /usr/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - web
