version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  node:
    build: ./front-end
    command: "npm start ./package.json"
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      - web

