# Generated by Django 2.1.4 on 2018-12-29 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitty', '0003_auto_20181212_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('L', 'User logged in'), ('R', 'User registered'), ('CK', 'New kitty created'), ('AK', 'User accepted joining the kitty'), ('DK', 'User declined joining the kitty'), ('WK', 'User is watiting for kitty requests')], max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
