# Generated by Django 2.1.4 on 2018-12-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0004_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
