# Generated by Django 2.1.4 on 2019-01-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0006_transaction_kitty_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('OP', 'Open'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='OP', max_length=2),
        ),
    ]
