# Generated by Django 2.1.4 on 2018-12-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181209_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile_1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='profile_2',
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
