# Generated by Django 2.1.4 on 2018-12-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact1', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact2', to='users.Profile'),
        ),
    ]
