# Generated by Django 2.1.4 on 2018-12-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181209_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
